### ISSUE TITLE
Too many errors, I don't know where to start...

### ISSUE THREAD

**Issue by noahaklem** [learn-co-curriculum/jsdom-task-lister-lite#8]
### Canvas Link

https://github.com/learn-co-curriculum/jsdom-task-lister-lite/blob/bfc5bbdb8afa7f8565b1ca83c1aaa033cbd6adf3/CONTRIBUTING.md

### Concern

This is the first time here so I'm not really sure what to do. However, this lesson seems to be opening up a server under localhost:8000. However, you run learn and basically have no idea that's what is happening. After learn runs, I am looking at something like this: 
    browser-sync  <=2.26.13
    Depends on vulnerable versions of browser-sync-client
    Depends on vulnerable versions of browser-sync-ui
    Depends on vulnerable versions of chokidar
    Depends on vulnerable versions of connect
    Depends on vulnerable versions of easy-extender
    Depends on vulnerable versions of eazy-logger
    Depends on vulnerable versions of http-proxy
    Depends on vulnerable versions of localtunnel
    Depends on vulnerable versions of micromatch
    Depends on vulnerable versions of qs
    Depends on vulnerable versions of serve-index
    Depends on vulnerable versions of serve-static
    Depends on vulnerable versions of socket.io
    Depends on vulnerable versions of socket.io-client
    Depends on vulnerable versions of ua-parser-js
    Depends on vulnerable versions of yargs
    node_modules/browser-sync
      learn-browser  *
      Depends on vulnerable versions of browser-sync
      Depends on vulnerable versions of mocha
      node_modules/learn-browser

62 vulnerabilities (6 low, 9 moderate, 39 high, 8 critical)

To address all issues, run:
  npm audit fix

miles and miles of this stuff. I run "npm audit fix" and it produces the same type of code.  This may all be normal but how would we, as students, know that? We come all this way using our terminal to run learn and yes, read a few errors but nothing in the Readme says this will happen. 

I guess a warning would be in order. This lab isn't set up like the labs we've encountered before. Probably a ton of behind the scenes stuff going on. That's fine but I think a warning would be good.

I suppose the next issue would be the actual coding. I received a warning in the beginning of the module about being on a "learn just enough to get by" but just read through some of the "deliverables" and "optional deliverables" in this lab. I figured somethings out on my own but I don't think I'm too far off when I say "you want me to do what with my 'learn just enough to get by' skills?" Sure, I can stumble for hours or days coding some of this stuff but is that really the right approach? I'm looking at the solution page like there's answers in there. There's not. I see new folders, code, syntax that hasn't been taught yet. 

Not really sure what to say. Just look through the lessons up to this point, then compare it with the answer/solution available in this lab. I suppose, afterwards, I would ask myself the question: is there a clear pathway that I can expect students to understand and recreate the same code as the solution provided (with minor differences)?

### Additional Context

na

### Suggested Changes

I guess a warning would be in order. This lab isn't set up like the labs we've encountered before. Probably a ton of behind the scenes stuff going on. That's fine but I think a warning would be good.

Not really sure what to say. Just look through the lessons up to this point, then compare it with the answer/solution available in this lab. I suppose, afterwards, I would ask myself the question: is there a clear pathway that I can expect students to understand and recreate the same code as the solution provided (with minor differences)?

**Comment by lizbur10** [comment]
Hi @noahaklem ! I'm so sorry you've run into problems with this lab!

This lab does not have tests so you do not need to run `learn test`. I have edited the instructions to make that clearer. Note that you may not see the update in your Canvas course, but it will be there for students moving forward.

As for all the warnings you got in your terminal, those are common. They are related to outdated code in the modules that were installed when you ran `learn` and need to be fixed by the authors of those modules. While these warnings would be of concern in a deployed app since they indicate potential security vulnerabilities, you can safely ignore them for labs.

If you still need help with how to go about completing this lab, you can reach out to your instructor or Section Lead, or use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

Thanks for contributing to the Flatiron School curriculum! 💙
